### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [ncwmail/edgar-wallace_the-just-men-of-cordova#1]
- [ ] The dash before the footnote at the end of chapter one is not an interruption but an obscuring of the name (per the scan; there is a space before the dash, unlike, e.g., the “I thought—” a few lines down), and should therefore be a 3em dash. See [SEMoS 8.7.7.8.5](https://standardebooks.org/manual/1.7.4/single-page#8.7.7.8.5).
- [ ] Similarly, the dash in the P⸺e a little further in the chapter is also an obscuring dash, and so should be a 2em dash. See [SEMoS 8.7.7.8.4](https://standardebooks.org/manual/1.7.4/single-page#8.7.7.8.4).
- [ ] The S. in “Dr S.” in ch. 1 should be tagged as a name abbreviation.
- [ ] Same for the J. in Colonel J. Black in ch. 2.
- [ ] You called the _Racing Calendar_ a newspaper in _Council of Justice_; since each calendar was several hundred pages, I think the journal that you use here is more appropriate, so would you mind submitting a PR to change it in CoJ? Thanks!
- [ ] The name being spelled at the end of chapter 2 should be all graphemes. It ends in “ley” here, but “l e y” (with spaces between) in the scans, and each of those should be a grapheme just like the other two letters.
- [ ] The question mark in “What do you mean ‘a bluff?’” in ch. 3 is not part of the quote, and so should be outside the single quotes. (Only commas and periods go inside the quotes in that situation.)
- [ ] There is a missing endnote in ch. 3 on “There’s a busy…”.
- [ ] There are quotes missing around ‘Four Just Men’ in multiple places that have them in the scans.
- [ ] Since the odds in ch. 5 aren’t a range, I believe that dash should be a figure dash rather than an en-dash. See [SEMoS 8.7.7.2](https://standardebooks.org/manual/1.7.4/single-page#8.7.7.2). I’ve asked Alex on the list to make sure.
- [ ] The series metadata is called “Four Just Men,” but the long description refers to it as the “Just Men” series. We should be consistent in referring to it.
- [ ] I believe there should be a comma after “financier” in the long description?
- [ ] Same for “Black’s” in the next paragraph.

**Comment by vr8hub** [comment]
Alex said on-list the en-dash was correct for the odds, so I removed that item from the list.
